[dependencies]
lazy_static = "1.4.0"
once_cell = "1.19.0"
vscode = { path = "../../rust-api/rust" }
wasm-bindgen = "0.2"
wit-bindgen = "0.21.0"

[lib]
crate-type = ["cdylib"]
path = "Source/lib.rs"

[package]
edition = "2021"
name = "vscode_example"
version = "0.1.0"
