[dependencies]
indexmap = "2.7"
lazy_static = "1.5.0"
once_cell = "1.20.3"
uuid = "1.13"
wit-bindgen = "0.39.0"

[lib]
path = "Source/lib.rs"

[package]
edition = "2024"
name = "vscode"
version = "0.1.0"
