[dependencies]
indexmap = "1.7"
lazy_static = "1.4.0"
once_cell = "1.19.0"
uuid = "0.8"
wit-bindgen = "0.24.0"

[lib]
path = "Source/lib.rs"

[package]
edition = "2021"
name = "vscode"
version = "0.1.0"
