[dependencies]
lsp-server = "0.7.8"
lsp-types = "0.97.0"
serde = "1.0.217"
serde_json = "1.0.138"
walkdir = "2"

[lib]
path = "Source/lib.rs"

[package]
edition = "2024"
name = "testbed_lsp_rust_server"
version = "0.1.0"
