[dependencies]
lsp-server = "0.7.6"
lsp-types = "0.95.1"
serde = "1.0.189"
serde_json = "1.0.107"
walkdir = "2"

[lib]
path = "Source/lib.rs"

[package]
edition = "2021"
name = "server"
version = "0.1.0"
